### ISSUE TITLE
The last observation of each episode is just the same as the first observation of the next episode.

### ISSUE THREAD

**Issue by CoolPhilChen** [herodrigues/robocup2d-tutorial#6]
Hi @herodrigues ! I observed something very weird when using `rcssserer`. I found that the last observation of each episode is just the same as the first observation of the next episode. That's to say the simulator doesn't give the state features of the ending state of an episode, but give the state features of the first state of the following episode. Do you know how to fix this problem? Any help is appreciated!

**Comment by herodrigues** [comment]
I'm not sure what causes this issue.
I'm trying to move this repo to the official rcsserver organization. There will have more support from the original creator and it'll be easier to fixes that.

**Comment by herodrigues** [comment]
I'm not sure what causes this issue.
I'm trying to move this repo to the official rcsoccersim organization. There we will have more support from the original creator and it'll be easier to fix issues like this one.

Also, I created this repo to be only a "get started". You can open this same issue in the official rcssserver repo here https://github.com/rcsoccersim/rcssserver

**Comment by CoolPhilChen** [comment]
ok. thanks a lot!
